In [4]:
import matplotlib.pyplot as plt 
import numpy as np 
from sklearn.decomposition import PCA 
from matplotlib.pyplot import imread 



In [6]:
img = imread("kaku.jpg")
img = img.astype(np.uint8)
img =img/2

[[[ 15  10   6]
  [ 11   6   2]
  [ 11   6   2]
  ...
  [ 14  44 255]
  [  8  38 250]
  [  8  38 250]]

 [[ 14   9   5]
  [ 13   8   4]
  [ 12   7   3]
  ...
  [ 14  44 255]
  [ 10  40 252]
  [ 10  40 252]]

 [[ 13   8   4]
  [ 14   9   5]
  [ 15  10   6]
  ...
  [ 15  45 255]
  [ 13  43 255]
  [ 12  42 254]]

 ...

 [[ 71  31  19]
  [ 73  33  21]
  [ 76  36  24]
  ...
  [ 59  23   7]
  [ 62  26  10]
  [ 66  30  14]]

 [[ 74  34  22]
  [ 75  35  23]
  [ 78  38  26]
  ...
  [ 66  30  14]
  [ 64  28  12]
  [ 65  29  13]]

 [[ 77  37  25]
  [ 77  37  25]
  [ 79  39  27]
  ...
  [ 72  36  20]
  [ 66  30  14]
  [ 65  29  13]]]


array([[[ 15,  10,   6],
        [ 11,   6,   2],
        [ 11,   6,   2],
        ...,
        [ 14,  44, 255],
        [  8,  38, 250],
        [  8,  38, 250]],

       [[ 14,   9,   5],
        [ 13,   8,   4],
        [ 12,   7,   3],
        ...,
        [ 14,  44, 255],
        [ 10,  40, 252],
        [ 10,  40, 252]],

       [[ 13,   8,   4],
        [ 14,   9,   5],
        [ 15,  10,   6],
        ...,
        [ 15,  45, 255],
        [ 13,  43, 255],
        [ 12,  42, 254]],

       ...,

       [[ 71,  31,  19],
        [ 73,  33,  21],
        [ 76,  36,  24],
        ...,
        [ 59,  23,   7],
        [ 62,  26,  10],
        [ 66,  30,  14]],

       [[ 74,  34,  22],
        [ 75,  35,  23],
        [ 78,  38,  26],
        ...,
        [ 66,  30,  14],
        [ 64,  28,  12],
        [ 65,  29,  13]],

       [[ 77,  37,  25],
        [ 77,  37,  25],
        [ 79,  39,  27],
        ...,
        [ 72,  36,  20],
        [ 66,  30,  14],
        [ 65,  29,  13]]